# Generated by Django 3.0.8 on 2020-07-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('im1', models.ImageField(upload_to='images/')),
                ('disc', models.CharField(max_length=500)),
            ],
        ),
    ]
