# Generated by Django 3.0.8 on 2020-07-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book1', '0002_book1_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('im1', models.ImageField(upload_to='images/')),
                ('disc', models.CharField(max_length=500)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
