# Generated by Django 3.0.8 on 2020-07-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book1', '0005_auto_20200708_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='uname',
            new_name='username',
        ),
    ]
