# Generated by Django 3.0.8 on 2020-07-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book1', '0006_auto_20200709_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='login',
            field=models.BooleanField(default=False),
        ),
    ]
