# Generated by Django 3.0.8 on 2020-07-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book1', '0007_users_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='cutomers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('emailid', models.CharField(max_length=30)),
                ('login', models.CharField(default='false', max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
