# Generated by Django 3.0.8 on 2020-07-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book1', '0008_auto_20200710_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutomers',
            name='emailid',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='cutomers',
            name='password',
            field=models.CharField(default='none', max_length=15),
        ),
        migrations.AlterField(
            model_name='cutomers',
            name='username',
            field=models.CharField(default='none', max_length=15),
        ),
    ]
