# Generated by Django 3.0.8 on 2020-07-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book1', '0009_auto_20200710_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutomers',
            name='emailid',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cutomers',
            name='login',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='cutomers',
            name='password',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='cutomers',
            name='username',
            field=models.CharField(max_length=15),
        ),
    ]
