# Generated by Django 3.0.8 on 2020-07-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book1', '0010_auto_20200711_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='book2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('im1', models.ImageField(upload_to='images/')),
                ('disc', models.CharField(max_length=500)),
                ('price', models.IntegerField(default=0)),
                ('cart1', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='book1',
        ),
    ]
