# Generated by Django 3.0.8 on 2020-07-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book1', '0011_auto_20200711_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book2',
            name='cart1',
        ),
    ]
