# Generated by Django 3.0.8 on 2020-07-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book1', '0012_remove_book2_cart1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='im1',
            field=models.FileField(upload_to='images/'),
        ),
    ]
