# Generated by Django 3.0.8 on 2020-07-17 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book1', '0013_auto_20200714_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book2',
            old_name='disc',
            new_name='Book_genre',
        ),
        migrations.RenameField(
            model_name='book2',
            old_name='name',
            new_name='Book_name',
        ),
        migrations.RenameField(
            model_name='book2',
            old_name='price',
            new_name='Book_price',
        ),
        migrations.RenameField(
            model_name='book2',
            old_name='im1',
            new_name='Image_file',
        ),
    ]
